### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by seeyourmind** [AliLotfi92/InfoMaxVAE#1]
when i ran `infoMaxVAE.py`, i got the error like:
```
Traceback (most recent call last):
  File "../infoMaxVAE.py", line 183, in <module>
    info_loss.backward()
  File "../lib/python3.8/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "../lib/python3.8/site-packages/torch/autograd/__init__.py", line 130, in backward
    Variable._execution_engine.run_backward(
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1000, 4]], which is output 0 of TBackward, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```
so, what can i do to fix this error?

**Comment by AliLotfi92** [comment]
Yeah, Sure! Give me a week

**Comment by AliLotfi92** [comment]
Would you clarify more? which code did you get this error?

**Comment by seeyourmind** [comment]
thanks for your reply, i think this error is caused by the version of pytorch.

**Comment by AliLotfi92** [comment]
Fixed the isuue with n

**Comment by AliLotfi92** [comment]
I fixed the issue, now you can install the newer versions of Pytorch and run the code! 
Thanks
